import Head from 'next/head'
import { Open_Sans } from 'next/font/google'
import Hero from '../../components/home/Hero'
import About from '../../components/home/About'
import Catering from '../../components/home/Catering'
import Footer from '../../components/global/Footer'
import Newsletter from '../../components/home/Newsletter'

const openSans = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gusteevos | Fine Dining</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={openSans.className}>
        <Hero />
        <About />
        <Catering />
        <Newsletter />
        <Footer />
      </main>
    </>
  )
}
